namespace Lantean.QBTMud.Theming
{
    /// <summary>
    /// Defines the palette color targets for theme editing.
    /// </summary>
    public enum ThemePaletteColor
    {
        Black,
        White,
        Primary,
        PrimaryContrastText,
        Secondary,
        SecondaryContrastText,
        Tertiary,
        TertiaryContrastText,
        Info,
        InfoContrastText,
        Success,
        SuccessContrastText,
        Warning,
        WarningContrastText,
        Error,
        ErrorContrastText,
        Dark,
        DarkContrastText,
        Surface,
        Background,
        BackgroundGray,
        DrawerText,
        DrawerIcon,
        DrawerBackground,
        AppbarText,
        AppbarBackground,
        LinesDefault,
        LinesInputs,
        TableLines,
        TableStriped,
        TableHover,
        Divider,
        DividerLight,
        Skeleton,
        GrayDefault,
        GrayLight,
        GrayLighter,
        GrayDark,
        GrayDarker,
        OverlayDark,
        OverlayLight,
        TextPrimary,
        TextSecondary,
        TextDisabled,
        ActionDefault,
        ActionDisabled,
        ActionDisabledBackground
    }
}
