using QBittorrent.ApiClient.Models;

namespace Lantean.QBTMud.Test.Infrastructure
{
    internal static class ClientTorrentFactory
    {
        internal static Torrent Create(
            string? hash = null,
            string? infoHashV1 = null,
            string? infoHashV2 = null,
            string? name = null,
            string? magnetUri = null,
            long? size = null,
            double? progress = null,
            int? downloadSpeed = null,
            int? uploadSpeed = null,
            int? priority = null,
            int? numberSeeds = null,
            int? numberComplete = null,
            int? numberLeeches = null,
            int? numberIncomplete = null,
            double? ratio = null,
            double? popularity = null,
            long? estimatedTimeOfArrival = null,
            TorrentState? state = null,
            bool? sequentialDownload = null,
            bool? firstLastPiecePriority = null,
            string? category = null,
            IReadOnlyList<string>? tags = null,
            bool? superSeeding = null,
            bool? forceStart = null,
            string? savePath = null,
            string? downloadPath = null,
            string? contentPath = null,
            string? rootPath = null,
            long? addedOn = null,
            long? completionOn = null,
            string? tracker = null,
            int? trackersCount = null,
            int? downloadLimit = null,
            int? uploadLimit = null,
            long? downloaded = null,
            long? uploaded = null,
            long? downloadedSession = null,
            long? uploadedSession = null,
            long? amountLeft = null,
            long? completed = null,
            int? connectionsCount = null,
            int? connectionsLimit = null,
            double? maxRatio = null,
            int? maxSeedingTime = null,
            int? maxInactiveSeedingTime = null,
            double? ratioLimit = null,
            int? seedingTimeLimit = null,
            int? inactiveSeedingTimeLimit = null,
            ShareLimitAction? shareLimitAction = null,
            long? seenComplete = null,
            long? lastActivity = null,
            long? totalSize = null,
            bool? automaticTorrentManagement = null,
            int? timeActive = null,
            long? seedingTime = null,
            double? availability = null,
            long? reannounce = null,
            string? comment = null,
            bool? hasMetadata = null,
            string? createdBy = null,
            long? creationDate = null,
            bool? isPrivate = null,
            long? totalWasted = null,
            int? piecesCount = null,
            long? pieceSize = null,
            int? piecesHave = null,
            bool? hasTrackerWarning = null,
            bool? hasTrackerError = null,
            bool? hasOtherAnnounceError = null,
            IReadOnlyList<TorrentTracker>? trackers = null)
        {
            return new Torrent(
                hash: hash,
                infoHashV1: infoHashV1,
                infoHashV2: infoHashV2,
                name: name,
                magnetUri: magnetUri,
                size: size,
                progress: progress,
                downloadSpeed: downloadSpeed,
                uploadSpeed: uploadSpeed,
                priority: priority,
                numberSeeds: numberSeeds,
                numberComplete: numberComplete,
                numberLeeches: numberLeeches,
                numberIncomplete: numberIncomplete,
                ratio: ratio,
                popularity: popularity,
                estimatedTimeOfArrival: estimatedTimeOfArrival,
                state: state,
                sequentialDownload: sequentialDownload,
                firstLastPiecePriority: firstLastPiecePriority,
                category: category,
                tags: tags,
                superSeeding: superSeeding,
                forceStart: forceStart,
                savePath: savePath,
                downloadPath: downloadPath,
                contentPath: contentPath,
                rootPath: rootPath,
                addedOn: addedOn,
                completionOn: completionOn,
                tracker: tracker,
                trackersCount: trackersCount,
                downloadLimit: downloadLimit,
                uploadLimit: uploadLimit,
                downloaded: downloaded,
                uploaded: uploaded,
                downloadedSession: downloadedSession,
                uploadedSession: uploadedSession,
                amountLeft: amountLeft,
                completed: completed,
                connectionsCount: connectionsCount,
                connectionsLimit: connectionsLimit,
                maxRatio: maxRatio,
                maxSeedingTime: maxSeedingTime,
                maxInactiveSeedingTime: maxInactiveSeedingTime,
                ratioLimit: ratioLimit,
                seedingTimeLimit: seedingTimeLimit,
                inactiveSeedingTimeLimit: inactiveSeedingTimeLimit,
                shareLimitAction: shareLimitAction,
                seenComplete: seenComplete,
                lastActivity: lastActivity,
                totalSize: totalSize,
                automaticTorrentManagement: automaticTorrentManagement,
                timeActive: timeActive,
                seedingTime: seedingTime,
                availability: availability,
                reannounce: reannounce,
                comment: comment,
                hasMetadata: hasMetadata,
                createdBy: createdBy,
                creationDate: creationDate,
                isPrivate: isPrivate,
                totalWasted: totalWasted,
                piecesCount: piecesCount,
                pieceSize: pieceSize,
                piecesHave: piecesHave,
                hasTrackerWarning: hasTrackerWarning,
                hasTrackerError: hasTrackerError,
                hasOtherAnnounceError: hasOtherAnnounceError,
                trackers: trackers);
        }
    }
}
