name: Build, Test, and Release Blazor WebAssembly App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: '6.x'

      - name: Determine Version
        id: gitversion
        run: $GITVERSION_PATH/gitversion /output json /showvariable FullSemVer
        shell: bash

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test --no-build --configuration Release

      - name: Publish (only on master)
        if: github.ref == 'refs/heads/master'
        run: dotnet publish -c Release -o output

      - name: Prepare Release ZIP
        if: github.ref == 'refs/heads/master'
        run: |
          cd output
          mv wwwroot public
          zip -r "../qbt-mud-v${{ steps.gitversion.outputs.FullSemVer }}.zip" public
        shell: bash

      - name: Create GitHub Release
        if: github.ref == 'refs/heads/master'
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.gitversion.outputs.FullSemVer }}
          release_name: Release v${{ steps.gitversion.outputs.FullSemVer }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: qbt-mud-v${{ steps.gitversion.outputs.FullSemVer }}.zip
          asset_name: qbt-mud-v${{ steps.gitversion.outputs.FullSemVer }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
